### ISSUE TITLE
Manage more than one run a day avoiding overwriting

### ISSUE THREAD

**Issue by slott56** [NoseySmurf/rss#2]
It also occurs to me that in its current form I shouldn't run this script more than once a day if I don't want to wipe the contents of the files created in https://github.com/NoseySmurf/rss/blob/master/rsstest15.lpy.py#L225-L227.

**Comment by slott56** [comment]
Yes. If you run a second time on a given day, the set of "new" items will be much, much shorter than any previous day. Indeed, it may be empty.

It's relatively easy to add a command-line option to avoid overwriting unless forced to.

**Comment by NoseySmurf** [comment]
Added strftime function to check if most recently retrieved data is from today.
